#!/bin/bash

filename=$(basename $1)
ext="${filename##*.}"
dir=$(dirname $0)

if [ $ext = "java" ]; then
    run="java_run"
elif [ $ext = "cpp" ]; then
    run="cpp_run"
fi

$dir/$run $1 < "$dir/input"